spring:
  application:
    name: uu-ms-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/uu-users?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver