spring:
  application:
    name: uu-ms-user
    version: 0.0.1
    description: User Microservice for UU.
  datasource:
    url: jdbc:mysql://localhost:3306/uu_users?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    default: local