server:
  port: 8100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uu_users?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
        healthcheck:
          enabled: true
      instance:
        preferIpAddress: true
        instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  endpoints:
    web:
      exposure:
        include: "*" # 开启所有监控端点
  endpoint:
    health:
      show-details: always # 显示详细健康信息
info:
  app.name: ${spring.application.name}
  app.description: ${spring.application.description}
  app.version: ${spring.application.version}
  app.build.time: ${timestamp}